### ISSUE TITLE
Goal 2: Back-end relay

### ISSUE THREAD

**Issue by danilowhk** [semaphore-protocol/taz-apps#4]
**Description**:

The relay will expose APIs to allow users to join groups and send their zero-knowledge proofs on-chain, to unlink the address of the person creating the proof from the proof itself. All transaction-related costs will therefore be paid from an account managed in the back-end.

**Tasks**:

- [x] Create API to add members to the on-chain group
- [x] Create APIs to broadcast signals on-chain
- [x] Create read-only APIs to get signal contents 
- [x] Create DB entity for invitation codes
- [x] Create DB entity for signals

**Comment by danilowhk** [comment]
- Need code Review
- Possible implementation of Subgraph fetching for performance
