### ISSUE TITLE
Goal 1: Voting mechanism

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/taz-apps#40]
**Tasks**:

- [x] Modal to inform people they have already voted
- [x] Save local variable for users who have already voted
- [x] Fix image bug
