### ISSUE TITLE
Goal 3: UI bugfixes and improvements

### ISSUE THREAD

**Issue by cedoor** [semaphore-protocol/taz-apps#43]
**Tasks**:

- [x] #45
- [x] Fix disconnect button JS error
- [x] Fix Art Gallery modal position
- [x] Fix Art Gallery modal height
