### ISSUE TITLE
Goal 4: TAZ - Q&A PWA

### ISSUE THREAD

**Issue by danilowhk** [semaphore-protocol/taz-apps#5]
**Description**:

The Q&A app will allow users to ask anonymous questions and answer those questions anonymously. Each user will be able to ask a limited number of questions and can only answer an existing question once.

**Tasks**:

- [x] Define the design
- [x] Show loading feedback
- [x] Set number of block confirmations before moving to the next step
- [x] Allow users to scan the identity QR code
- [x] Show the list of existing questions/answers
- [x] Allow users to generate their questions
- [x] Allow users to answer existing questions
