### ISSUE TITLE
Goal 5: TAZ - Art Wall PWA

### ISSUE THREAD

**Issue by danilowhk** [semaphore-protocol/taz-apps#6]
**Description**:

The Art Wall app will allow users to co-create drawings with other users anonymously.

**Tasks**:

- [x] Define the design 
- [x] Allow users to scan the identity QR code
- [x] Show a wall with all the existing drawings
- [x] Allow users to add their drawings
- [x] Blacklisting from etherscan
- [x] Blacklisting Tiles
