### ISSUE TITLE
Goal 3: TAZ contract

### ISSUE THREAD

**Issue by danilowhk** [semaphore-protocol/taz-apps#7]
**Description**:

The TAZ contract will be linked to the `Semaphore.sol` contract on Goerli and will allow the back-end to add members to the TAZ group and verify zero-knowledge proofs on-chain, and thus broadcast anonymous signals.

**Tasks**:

- [x] Action 1: allow group members to send questions (hash)
- [x] Action 2: allow group members to answer questions (hash)
- [x] Action 3: allow group members to broadcast drawing (hash)  
- [x] Make the contract the group admin
